### ISSUE TITLE
Composite builder example is broken

### ISSUE THREAD

**Issue by hvanhovell** [weld-project/weld#161]
When I execute the composite builder example in the repl:
```
let b1 = appender[i32];
let b2 = appender[i32];
let data = [1, 2, 3];
let bs = for(
  data,
  {b1, b2},
  |bs: {appender[i32], appender[i32]}, i: i64, n: i32| {merge(bs.$0, n), merge(bs.$1, 2 * n)}
);
result(bs)
```
It fails with the following error:
```
thread 'main' has overflowed its stack
fatal runtime error: stack overflow
Abort trap: 6
```
Also note that the example in the documentation is not correct.

I am on mac OS X 10.11.6.

**Comment by sppalkia** [comment]
Hi @hvanhovell,

Thanks for trying out the project and finding the issues! Some of the syntax errors are because the documentation was ported over from an old implementation of the project.

I fixed the stack overflow error in #164, along with the documentation example. Please don't hesitate to continue raising any more bugs you may encounter; we'll be sure to take a look at them.

-Shoumik
