### ISSUE TITLE
why weldnumpy offical examples slower than numpy

### ISSUE THREAD

**Issue by yangzhg** [weld-project/weld#340]
The example code in https://www.weld.rs/weldnumpy/ runs slower than numpy 
![image](https://user-images.githubusercontent.com/9098473/38463029-0a0cd58a-3b23-11e8-96a6-e2fd75436eb4.png)

**Comment by sppalkia** [comment]
Hey @yangzhg,

Thanks for pointing this out! This was due to a bunch of transforms in Weld that we had not merged in to master/the pyweld distribution. We just opened a PR (#341) that resolves this -- you should see much better performance when the are merged in :)

**Comment by sppalkia** [comment]
Hi @yangzhg,

That example is probably a little odd because it seems like it doesn't include compile time (just going from how small the overall runtimes are) -- we should update it.

That said, you won't see speedups unless you're data is somewhat large, because Weld does have some fixed overhead to compile the program and to set up its runtime once it launches. Here's a program with some moderately sized data that produces a ~10x speedup on my laptop on a single thread:

```
import weldnumpy as wnp
import numpy as np
import time

from weld.bindings import *

size=50000000

def test(a, b, weld=False, size):
    for i in xrange(20):
        a = a + b

    if weld:
        a = a.evaluate()
    return a

a = np.ones(size, dtype="float")
b = np.ones(size, dtype="float")

start = time.time()
result1 = test(a, b, weld=False, size=size)
end = time.time()
print end - start

a = wnp.array(np.ones(size, dtype="float"))
b = wnp.array(np.ones(size, dtype="float"))

start = time.time()
result2 = test(a, b, weld=True, size=size)
end = time.time()
print end - start

# Correctness check
assert np.allclose(result1, result2)
```

and the laptop specs: 
MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
CPU: 2.9 GHz Intel Core i5
Memory: 16 GB 2133 MHz LPDDR3

In general, you'll see the biggest speedups when you have (a) lots of data and (b) lots of operations that are chained together.
